export enum ErrorCode {
    PORT_NOT_FOUND = "PORT_NOT_FOUND",
    PORT_KIND_MISMATCH = "PORT_KIND_MISMATCH",
    PORT_DIRECTION_MISMATCH = "PORT_DIRECTION_MISMATCH",
    PROTOCOL_NOT_FOUND = "PROTOCOL_NOT_FOUND",
    PROTOCOL_CONSTRAINTS_MISMATCH = "PROTOCOL_CONSTRAINTS_MISMATCH",
}
